# Generated by Django 3.0.8 on 2020-12-31 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20201229_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='category',
            field=models.CharField(choices=[('FS', 'Fashion'), ('TY', 'Toys'), ('EE', 'Electronics'), ('HM', 'Home'), ('GR', 'Garden')], default='EE', max_length=2),
        ),
    ]
