# Generated by Django 3.0.8 on 2020-12-31 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listings_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='published',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
